abstract class CurrencyConversionViewModelState{}
class InitialCurrencyConversionStatus extends CurrencyConversionViewModelState {}
class LoadingCurrencyConversionStatus extends CurrencyConversionViewModelState{}
class LoadedCurrencyConversionStatus extends CurrencyConversionViewModelState{}


